name: Discord Notification

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Set Date
        run: echo "DATE=$(date +'%d/%m/%Y')" >> $GITHUB_ENV

      - name: Send message to Discord
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: https://discord.com/api/webhooks/XXXXX/XXXXX
          DISCORD_USERNAME: Golden Brown RP
          DISCORD_AVATAR: https://i.imgur.com/4M34hi2.png
          DISCORD_MESSAGE: |
            ðŸŸ¡ **[GoldenBrown.main]**
            ${{ github.event.head_commit.message }}
            ðŸ“… ${{ env.DATE }}